//获取项目数据
export const FETCH_PROJECT_DATA_BEGIN = 'FETCH_PROJECT_DATA_BEGIN';
export const FETCH_PROJECT_DATA_SUCCESS = 'FETCH_PROJECT_DATA_SUCCESS';
export const FETCH_PROJECT_DATA_FAILURE = 'FETCH_PROJECT_DATA_FAILURE';
