//获取用户所有项目信息
export const FETCH_PROJECTS_BEGIN = 'FETCH_PROJECTS_BEGIN';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECT_SUCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const SUBMIT_SELECTED_BEGIN = 'SUBMIT_SELECTED_BEGIN';
export const SUBMIT_SELECTED_SUCCESS = 'SUBMIT_SELECTED_SUCCESS';
export const SUBMIT_SELECTED_FAILURE = 'SUBMIT_SELECTED_FAILURE';

//是否显示对话框
export const IS_SHOW = 'IS_SHOW';
