//获取项目数据
export const FETCH_PROJECT_DATA_BEGIN = 'FETCH_PROJECT_DATA_BEGIN';
export const FETCH_PROJECT_DATA_SUCCESS = 'FETCH_PROJECT_DATA_SUCCESS';
export const FETCH_PROJECT_DATA_FAILURE = 'FETCH_PROJECT_DATA_FAILURE';
//创建新项目
export const CREATE_PROJECT_DATA_BEGIN = 'CREATE_PROJECT_DATA_BEGIN';
export const CREATE_PROJECT_DATA_SUCCESS = 'CREATE_PROJECT_DATA_SUCCESS';
export const CREATE_PROJECT_DATA_FAILURE = 'CREATE_PROJECT_DATA_FAILURE';

//获取用户所有项目信息
export const FETCH_PROJECTS_BEGIN = 'FETCH_PROJECTS_BEGIN';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECT_SUCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
