export const FETCH_PROJECT_DATA_BEGIN = 'HOME_FETCH_PROJECT_DATA_BEGIN';
export const FETCH_PROJECT_DATA_SUCCESS = 'FETCH_PROJECT_DATA_SUCCESS';
export const FETCH_PROJECT_DATA_FAILURE = 'FETCH_PROJECT_DATA_FAILURE';
