//获取用户所有项目
export const FETCH_PROJECTS_BEGIN = 'FETCH_USER_PROJECTS_BEGIN';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_USER_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILUR = 'FETCH_USER_PROJECTS_FAILUR';
//项目选择
export const PROJECTS_SELECT = 'PROJECTS_SELECT';
export const PROJECTS_CLOSE = 'PROJECTS_SELECT';

//创建项目
export const CREATE_USER_PROJECT = 'CREATE_USER_PROJECT';
